name: checkSyntax
on: [push]
jobs:
  Check-Syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Check Syntax
        run: python3 projet.py check_syntax
