name: config pyhton
on: [pull_request, workflow_dispatch]
jobs:
  configPython:
    runs-on: unbuntu-lastest
    steps:
    - uses: actions/checkout@v3
    - uses: action/setup-python@v4
      with:
        python-version: '3.10'
    - run: python main.py
      
    
    
