name: Docker push GCR

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 'Set up Cloud Auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCLOUD_KEY }}
    
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: esirem

      - name: Configure Docker using GCLOUD
        run: gcloud auth configure-docker

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          # Emplacement du Dockerfile
          file: Dockerfile
          tags: eu.gcr.io/esirem/4a_ilc/ghys_milhet/cicd:${{ github.ref_name }}
          # Emplacement des fichiers 
          context: ""
          push: true
